### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed

### ISSUE THREAD

**Issue by ValleyInforge** [J-E-L-E-Dev/laravelWebApp#3]
Hello!

First of all: thanks!

It work! But In my console I see this error on serviceworker.js:1
Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed

I see this error in local and also in shared host namecheap server.

Can you help me?

My serviceworker.js is the default one.

**Comment by J-E-L-E-Dev** [comment]
The addAll method is used to add the configured files to the cache.

This method is located in the serviceworker.js file within the app/public directory.

The filesToCache array should be the part that presents an error.

This array is a list of the views and files that you want to save in the cache. If you have customized the offline view or want to create your own offline view, you can do so by creating a route with the name "offline".

For example:

 Route::get('offline', function(){
    return view('vendor/laravelwebapp/offline');
});

Make sure that the files you want to save in the cache exist in the public folder of your project.

**Comment by J-E-L-E-Dev** [comment]
> Hello!
> 
> First of all: thanks!
> 
> It work! But In my console I see this error on serviceworker.js:1 Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed
> 
> I see this error in local and also in shared host namecheap server.
> 
> Can you help me?
> 
> My serviceworker.js is the default one.


Hello, it's a pleasure.
The addAll method is used to add the configured files to the cache.

This method is located in the serviceworker.js file within the app/public directory.

The filesToCache array should be the part that presents an error.

This array is a list of the views and files that you want to save in the cache. If you have customized the offline view or want to create your own offline view, you can do so by creating a route with the name "offline".

For example:

Route::get('offline', function(){
return view('vendor/laravelwebapp/offline');
});

Make sure that the files you want to save in the cache exist in the public folder of your project.
